services:


    coreshop.inventory.availability_checker.default:
        alias: 'coreshop.inventory.availability_checker.advanced'
        public: true

    coreshop.inventory.availability_checker.composite: '@CoreShop\Bundle\AdvancedInventoryBundle\Checker\CompositeAvailabilityChecker'
    CoreShop\Bundle\AdvancedInventoryBundle\Checker\CompositeAvailabilityChecker:

    CoreShop\Bundle\AdvancedInventoryBundle\Checker\DefaultAvailabilityChecker:
        arguments:
            - '@CoreShop\Component\Inventory\Checker\AvailabilityChecker'
        tags:
            - { name: coreshop.inventory.availability_checker, priority: -900 }



